### ISSUE TITLE
Redirects don't encode URL now

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-portal-generator#10]
It seems the NE (no escape) tag breaks URLs with percent-encoding. Going to:

http://ondemand3-dev.hpc.osc.edu/pun/sys/files/api/v1/fs/users/appl/jnicklas/ttt/test%25test/

redirects me to:

https://ondemand3-dev.hpc.osc.edu:443/pun/sys/files/api/v1/fs/users/appl/jnicklas/ttt/test%test/

instead of:

https://ondemand3-dev.hpc.osc.edu/pun/sys/files/api/v1/fs/users/appl/jnicklas/ttt/test%25test/

this was caused by the fix to #9

**Comment by nickjer** [comment]
It seems the same behavior as above is observed when logging in with mod_auth_openidc and it redirects me back to the page I originally wanted. Meaning, the path of the URL loses its URL encoding but the query params maintain their URL encoding.

**Comment by nickjer** [comment]
I am unable to find a way to escape the `%` above without also escaping the `/` above. I am leaning towards not fixing this since mod_auth_openidc behaves the same.

**Comment by nickjer** [comment]
A relevant question posed on serverfault:

http://serverfault.com/questions/331899/apache-mod-rewrite-double-encodes-query-string-on-redirect

**Comment by nickjer** [comment]
Another option is I add Lua code to handle the dynamic redirect as this seems to be a bug in mod_rewrite according to the above serverfault thread.

**Comment by basilgohar** [comment]
@nickjer That issue in serverfault is over 5 years old and the alleged commit to fix it is over 6 years old.  Do you know which version(s) of Apache HTTP should have this fix?

**Comment by nickjer** [comment]
None do. I think this can be closed as the current behavior covers majority of the use-cases.

**Comment by basilgohar** [comment]
Okay, then go ahead and close it.

**Comment by nickjer** [comment]
Won't fix as this is a rare edge case, httpd has yet to patch this, and we mimic the behavior of `mod_auth_openidc`.
