### ISSUE TITLE
Apache should offer a /logout URL so the dashboard (and other apps) do not have to know how to log out

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood-portal-generator#6]
Originally posted in https://github.com/OSC/ood-dashboard/issues/34

Before we just had CILogon and I had logout be hardcoded into the dashboard.

The code changes I made to support logout for both CILogon and Shibboleth were at https://github.com/OSC/ood-dashboard/pull/33/files

1. In a .env.local file OOD_DASHBOARD_LOGOUT_URL could be set to specify the logout URL to redirect to.
2. If OOD_DASHBOARD_LOGOUT_URL is not set, the logout option would not appear on the dashboard.

Since the dashboard doesn't know what auth method is being used, it would be better if Apache was configured to have a `/logout` and perhaps always have this.

1. For basic auth or in the case that logout is not supported, `/logout` could display a simple page asking the user to completely exit out of their browser in order to check out. Or clear cache. Etc. Just provide directions.
2. For other auth methods, `/logout` would do what it normally does right now: redirect to the OIDC logout URL and set the redirect_url after logout is completed to go back to the dashboard, so you are presented again with a login page.

This way, the dashboard can always show a link to `/logout` for OOD and `/logout` will always be the same URL for the dashboard.

**Comment by nickjer** [comment]
> For basic auth or in the case that logout is not supported, /logout could display a simple page asking the user to completely exit out of their browser in order to check out. Or clear cache. Etc. Just provide directions.

This would increase the complexity of a default install, as it would require an html document that may or may not be branded that would have to be installed/copied "probably" under `/var/www/ood/public/logout.html` (assuming the sys admin enables support for the `public/` uri). Then we'd specify under the logout `Location` directive something like...

```
<Location "/logout">
  Redirect 302 / /public/logout.html
</Location>
```
A typical install will run `sudo rake install`, so do we overwrite the html document if it is newer, do we leave it alone if it already exists? Seems like a lot of work for just basic auth. But it is do-able.

For the other auth logouts, it seems simple enough as they are just redirects to the authentication module's logout resources. They don't have any local dependencies.

**Comment by ericfranz** [comment]
or be explicit:

```
<Location "/logout">
  Redirect 302 / /public/basic_auth_logout.html
</Location>
```

A `sudo rake install` could just always put a `/public/basic_auth_logout.html` there. No harm if it is aways there. We could make an html page that was simple and not branded.

I'm sure we could come up with a way that the default install steps didn't change.

**Comment by nickjer** [comment]
> A `sudo rake install` could just always put a `/public/basic_auth_logout.html` there. No harm if it is aways there.

The problem is if a sys admin edits the file with branding or other modifications. A `sudo rake install` would overwrite all the changes.

Also, there is the question if the sys admin disables the public URI completely. Because of that interdependence between the public URI and basic auth logout, what would we do?

**Comment by ericfranz** [comment]
Discussed offline. We will add a new uri `/logout` that will simply provide a logout URL to send the user to. For basic auth, it will redirect the user to `/pun/sys/dashboard/logout` which will instruct the user to close the browser completely to end their session.
